site_for_learning/myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .views import (
    set_cookie_view,
    get_cookie_view,
    set_session_view,
    get_session_view,
    # logout_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    ProfileView,
    UserListView,
    HelloView,

)

app_name = "myauth"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"),
    path("hello/", HelloView.as_view(), name="hello"),
    # path("logout/", logout_view, name="logout"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", UserListView.as_view(), name="users_list"),
    path("profile/<int:pk>", ProfileView.as_view(), name="profile"),


    path("cookie/get", get_cookie_view, name="cookie-get"),
    path("cookie/set", set_cookie_view, name="cookie-set"),
    path("session/set", set_session_view, name="session-set"),
    path("session/get", get_session_view, name="session-get"),

    path("about-me/", AboutMeView.as_view(), name="about-me"),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

site_for_learning/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from django.views.decorators.cache import cache_page

from . import sitemap
from .views import (
    ShopIndexView,
    GroupsListView,
    ProductsListView,
    ProductDetailsView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrdersListView,
    OrderDetailView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    ProductsDataExportView,
    OrdersDataExportView,
    ProductViewSet,
    OrderViewSet,
    LatestProductsFeed,
    UserOrdersListView,
    UserOrdersExportView,
)


app_name = 'shopapp'

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    # path("", cache_page(60 * 2)(ShopIndexView.as_view()), name='index'),
    path("", ShopIndexView.as_view(), name='index'),
    path("groups/", GroupsListView.as_view(), name='groups_list'),
    path("products/", ProductsListView.as_view(), name='products_list'),
    path("products/create/", ProductCreateView.as_view(), name='product_create'),
    path("products/export/", ProductsDataExportView.as_view(), name='product_export'),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name='product_details'),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name='product_update'),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name='product_delete'),

    path("orders/", OrdersListView.as_view(), name='orders_list'),
    path("orders/create/", OrderCreateView.as_view(), name='order_create'),
    path("orders/export/", OrdersDataExportView.as_view(), name='order_export'),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name='order_details'),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name='order_update'),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name='order_delete'),

    path("api/", include(routers.urls)),

    path("products/latest/feed/", LatestProductsFeed(), name='products_feed'),

    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name='user_order_list'),
    path("users/<int:user_id>/orders/export/", UserOrdersExportView.as_view(), name='user_orders_export'),
]

site_for_learning/site_for_learning/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
    SpectacularRedocView,
)
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('learnapiapp.urls')),
    path('blog/', include('BlogApp.urls')),
]

urlpatterns += i18n_patterns(
path('admin/doc/', include('django.contrib.admindocs.urls')),
     path('admin/', admin.site.urls),
     path('myauth/', include('myauth.urls')),
     path('shop/', include('shopapp.urls')),
     path(
           'sitemap.xml',
            sitemap,
            {"sitemaps": sitemaps},
            name="django.contrib.sitemaps.view.sitemap",
          ),

     # path(
     #        'sitemap-<section>.xml',
     #        sitemap,
     #        {"sitemaps": sitemaps},
     #        name="django.contrib.sitemaps.views.sitemap",
     #    ),


)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include('debug_toolbar.urls')),
    )

site_for_learning/shopapp/forms.py
from django import forms
from .models import Product, Order
from django.contrib.auth.models import Group


from django.contrib.auth.models import AnonymousUser

# from django.core import validators

# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(min_value=1, max_value=100000, decimal_places=2)
#     description = forms.CharField(
#         label="Product description",
#         widget=forms.Textarea(attrs={"rows": 5, "cols": 30}),
#         validators=[validators.RegexValidator(
#             regex=r"great",
#             message="Field must contain word 'great'"
#                     )]


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview"

    # images = forms.ImageField(widget=forms.ClearableFileInput(attrs={"multiple": True}))
    images = MultipleFileField()

# class ProductForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = "name", "price", "description", "discount", "preview"


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "delivery_address", "promocode", "products", "user"


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = "name",


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

site_for_learning/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view для интернет-магазина: по товарам, заказам и т.д.
"""
import logging
from django.core import serializers
from django.contrib.syndication.views import Feed


from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import (
    HttpResponse,
    HttpRequest,
    HttpResponseRedirect,
    JsonResponse,
)
from timeit import default_timer
from django.contrib.auth.models import Group, User
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

# from site_for_learning.settings import LOGIN_URL
from .common import common_read_csv_file
from .forms import ProductForm, OrderForm, GroupForm
from .models import Product, Order
from django.views import View
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from drf_spectacular.utils import(
    extend_schema,
    OpenApiResponse,
)
from .serializer import ProductSerialize, OrderSerialize

from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.decorators import action
from rest_framework.parsers import MultiPartParser

from django_filters.rest_framework import DjangoFilterBackend
from csv import DictWriter
from django.utils.decorators import method_decorator
from django.core.cache import cache

log = logging.getLogger(__name__)


class LatestProductsFeed(Feed):
    title = "Products (latest)"
    link = reverse_lazy("shopapp:products_list")

    def items(self):
        return (
            Product.objects
            .filter(archived=False)
            .order_by("-create_at")[:5]
        )

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:10]


@extend_schema(description='Product views CRUD')
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product.

    Полный CRUD для сущностей товара.
    """
    model = Product
    queryset = Product.objects.all()
    serializer_class = ProductSerialize
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]

    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @extend_schema(
        summary='Get one product by id',
        description='Retrieves **product**, returns 404 if not found',
        responses={
            200: ProductSerialize,
            404: OpenApiResponse(description='Empty response, product by id not found'),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @method_decorator(cache_page(60*2))
    def list(self, *args, **kwargs):
        return super().list(*args, **kwargs)

    @action(methods=['get'], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type='text/csv')
        filename = "products-export.csv"
        response["Content-Desposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            'name',
            'description',
            'price',
            'discount',
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()
        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })

        return response

    @action(
        methods=['post'],
        detail=False,
        parser_classes=[MultiPartParser],
    )
    def upload_csv(self, request):
        products = common_read_csv_file(
            file=request.FILES["file"].file,
            encoding=request.encoding,
            model=self.model
        )
        self.model.save_csv(products)

        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


class OrderViewSet(ModelViewSet):
    """
    Набор представлений для действий над Order.

    Полный CRUD для сущностей заказа.
    """

    queryset = Order.objects.all()
    serializer_class = OrderSerialize
    filter_backends = [
        DjangoFilterBackend,
        OrderingFilter,
    ]

    filterset_fields = [
        "delivery_address",
        "promocode",
        "products",
    ]

    ordering_fields = [
        "user",
        "delivery_address",
    ]


class ShopIndexView(View):
    """Представление для shop."""

    def get(self, request: HttpRequest) -> HttpResponse:
        """Метод  обрабатывает get-запрос для страницы shop-index.html."""
        countries = {
            ('Russia', 143),
            ('Belarus', 9),
            ('India', 1423),
        }
        context = {
            'time_running': default_timer(),
            'countries': countries,
            'items': 5,
        }
        log.debug("Countries for shop index: %s", countries)
        log.info("Rendering shop index")
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    """Представление для групп."""

    def get(self, request: HttpRequest) -> HttpResponse:
        """Метод  обрабатывает get-запрос для страницы groups-list.html."""
        form = GroupForm()
        context = {
            "groups": Group.objects.prefetch_related('permissions').all(),
            "form": form,
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        """Метод  обрабатывает post-запрос для страницы groups-list.html."""
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


# class ProductDetailsView(View):
#     def get(self, request: HttpRequest, pk: int) -> HttpResponse:
#         product = get_object_or_404(Product, pk=pk)
#         context = {
#             "product": product,
#         }
#         return render(
#           request,
#           'shopapp/product-details.html',
#           context=context
#           )


class ProductDetailsView(DetailView):
    """Представление для деталей товаров."""

    template_name = 'shopapp/product-details.html'
    model = Product
    queryset = Product.objects.prefetch_related("images")
    context_object_name = "product"


# class ProductsListView(TemplateView):
#     template_name = 'shopapp/products-list.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["products"] = Product.objects.all()
#         return context


class ProductsListView(ListView):
    """Представление для набора товаров."""

    template_name = 'shopapp/products-list.html'
    # model = Product
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)


# def products_list(request: HttpRequest) -> HttpResponse:
#     """Ф-я view для вывода всех продуктов """
#     context = {
#         "products": Product.objects.all()
#     }
#     return render(request, 'shopapp/products-list.html', context=context)


# def create_product(request: HttpRequest) -> HttpResponse:
#     """ Ф-я view для создания продукта на странице """
#     if request.method == "POST":
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             # name = form.cleaned_data["name"]
#             # price = form.cleaned_data["price"]
#             # Product.objects.create(**form.cleaned_data)
#
#             form.save()
#             url = reverse("shopapp:products_list")
#             return redirect(url)
#     else:
#         form = ProductForm()
#     context = {
#         "form": form,
#     }
#     return render(request, 'shopapp/create-product.html', context=context)


class ProductCreateView(PermissionRequiredMixin, CreateView):
    """
    Представление для создания нового товара.

    Создание новой сущности товара - для пользователей с данными правами.
    """

    # template_name = 'shopapp/product-details.html'
    permission_required = "shopapp.add_product"
    model = Product
    # fields = "name", "price", "description", "discount"
    form_class = ProductForm
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        super().form_valid(form)
        return HttpResponseRedirect(reverse_lazy('shopapp:products_list'))


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name_suffix = "_update_form"

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            Product.objects.create(
                product=self.object,
                image=image,
            )
        return response

    def test_func(self):
        no_superuser_get_access = False
        is_true_permission = False

        product_author = self.get_object().created_by # Product.objects.select_related("created_by").get(pk=self.get_object().id)
        if product_author == self.request.user:
            no_superuser_get_access = True

        user_permission = self.request.user.get_user_permissions()
        if "shopapp.change_product" in user_permission:
            is_true_permission = True

        return any([self.request.user.is_superuser, no_superuser_get_access, is_true_permission])

    def get_success_url(self):

site_for_learning/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        Base Title
      {% endblock %}
    </title>

    <style>
       {% block style %}

       {% endblock %}

    </style>

</head>
<body>
 {% block body %}
   Base Body
 {% endblock %}
</body>

<div>
    {% now 'H:i' %}
</div>

<div>
    {% now 'l' as current_weekday %}
    {{current_weekday}}
</div>

</html>

site_for_learning/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1> Create a new product </h1>
    <div>
        <form method="post" >
            {% csrf_token %}

            {{form.as_p}}

            <button type="submit">
                Create
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Back to products list
        </a>
    </div>
{% endblock %}

site_for_learning/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups list
{% endblock %}

{% block body %}
  <h1> Groups: </h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit"> Create </button>
    </form>
  </div>
  <div>
    <ul>
        {% for group in groups %}
          <li>
            <div> {{ group.name }} </div>
            <ul>
              {% for permission in group.permissions.all %}
              <li>
                {{permission.name}}
                (<code> {{permission.codename}} </code>)
              </li>
              {% endfor %}
            </ul>
          </li>

        {% empty %}
          No groups
        {% endfor %}
    </ul>
  </div>

{% endblock %}

</html>

site_for_learning/shopapp/templates/shopapp/order_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}

    <li>
        <a href="{% url 'admin:import_orders_csv' %}" class="addlink" >
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

site_for_learning/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete {{ object.delivery_address }}
{% endblock %}

{% block body %}
<h1> Are you sure you want to delete order #{{ object.pk }} by address: {{ object.delivery_address }} </h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">
            Back to order
        </a>
    </div>

    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"> Delete </button>
        </form>
    </div>

{% endblock %}

site_for_learning/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order # {{ objects.pk }}
{% endblock %}

{% block body %}
  <h1> Order # {{ object.pk }} </h1>

  <div>
         <p> --------------------------- </p>
         <p> Order by {% firstof object.user.firstname order.user.username %} </p>
         <p> Promocode: <code> {{ object.promocode }} </code> </p>
         <p> Delivery address: {{ object.delivery_address }} </p>

         <div>
             Products in order:
         </div>
         <ul>
             {% for product in object.products.all %}
                 <li> {{product.name}} for ${{product.price}} </li>
             {% endfor %}
         </ul>

  </div>

  <div>
      <a href="{% url 'shopapp:order_update' pk=object.pk %}">
          Update order
      </a>
  </div>

  <div>
      <a href="{% url 'shopapp:order_delete' pk=object.pk %}">
          Dalete order
      </a>
  </div>

  <div>
      <a href="{% url 'shopapp:orders_list' %}">
          Back to orders
      </a>
  </div>

{% endblock %}

site_for_learning/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1> Create a new order </h1>
    <div>
        <form method="post" >
            {% csrf_token %}

            {{form.as_p}}

            <button type="submit">
                Create
            </button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:orders_list' %}">
            Back to orders list
        </a>
    </div>
{% endblock %}

site_for_learning/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
  <div>
          {% for user, orders in object_list.items %}
              <h4>
                  User
                  <a href = "{% url 'shopapp:user_order_list' user_id=user.pk %}">
                    {{ user.username }}
                  </a>
                  completed following orders:
              </h4>

          {% cache 100 cache_order_list user.pk %}
              {% for order in orders %}
              <div>
                <ul>

                    <p> <a href = "{% url 'shopapp:order_details' pk=order.pk %}"> Details #{{ order.pk }}</a> </p>
                    <p> Order by {% firstof order.user.firstname order.user.username %} </p>
                    <p> Promocode: <code> {{ order.promocode }} </code> </p>
                    <p> Delivery address: {{ order.delivery_address }} </p>

                    <div>
                        Products in order:
                    </div>

                    <ul>
                        {% for product in order.products.all %}
                            <li> {{product.name}} for ${{product.price}} </li>
                        {% endfor %}
                    </ul>

                </ul>
                      {% empty %}
                       <div> User has no orders yet </div>
              {% endfor %}
              </div>
          {% endcache %}
        {% endfor %}

  </div>

  <div>
      <a href="{% url 'shopapp:order_create' %}">
          Create a new order
      </a>
  </div>


{% endblock %}

site_for_learning/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block body %}

    <h1> {% translate 'Product' %}<strong> {{product.name}} </strong> </h1>
    <div>
        <div> {% translate 'Description' %}: <em> {{ product.description }} </em> </div>
        <div> {% translate 'Price' %}: {{ product.price }} </div>
        <div> {% translate 'Discount' %}: {{ product.discount}} </div>
        <div> {% translate 'Archived' %}: {{ product.archived}} </div>


        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}


        <h3> {% translate 'Images' %} </h3>

        <div>
          {% blocktranslate count image_count=product.images.all|length %}
             There is only one image
             {% plural %}
             There are {{ image_count }} images.
          {% endblocktranslate %}
        </div>

        <div>
            {% if product.images.all %}
                {% for image in product.images.all %}
                <div>
                    <img src="{{ image.image.url}}" alt="image.image.name">
                    <div> {{ image.description }} </div>
                </div>
                {% endfor %}
            {% else %}
                {% blocktranslate %}
                <div> No images uploaded yet </div>
                {% endblocktranslate %}
            {% endif %}




        </div>
    </div>

   {% url 'shopapp:product_update' pk=product.pk as shopapp_product_update_url %}
   {% url 'shopapp:product_delete' pk=product.pk as shopapp_product_delete_url %}
   {% url 'shopapp:products_list' as shopapp_product_list_url %}

   {% blocktranslate %}
   <div>
       <a href="{{ shopapp_product_update_url }}"> Update product </a>
   </div>
   <div>
       <a href="{{ shopapp_product_delete_url }}"> Archive product </a>
   </div>
   <div>
       <a href="{{ shopapp_product_list_url }}"> Back to products list </a>
   </div>
   {% endblocktranslate %}

{% endblock %}

site_for_learning/shopapp/templates/shopapp/product_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}

    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink" >
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

site_for_learning/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
<h1 xmlns="http://www.w3.org/1999/html"> Are you sure you want to archive {{ object.name }} </h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">
            Back to product
        </a>
    </div>

    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"> Archive </button>
        </form>
    </div>

{% endblock %}

site_for_learning/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
   <h1> Create product </h1>
   <div>
       <form method="post" enctype="multipart/form-data">
           {% csrf_token %}

           {{ form.as_p }}

           <button type="submit"> Create </button>
       </form>
   </div>
   <div>
       <a href="{% url 'shopapp:products_list' %}">
           Back to products list
       </a>
   </div>
{% endblock %}

site_for_learning/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update product
{% endblock %}

{% block body %}
   <h1> Update product </h1>
   <div>
       <form method="post" enctype="multipart/form-data">
           {% csrf_token %}

           {{ form.as_p }}

           <button type="submit"> Update </button>
       </form>
   </div>
   <div>
       <a href="{% url 'shopapp:product_details' pk=object.pk %}">
           Back to product # {{ object.pk }}
       </a>
   </div>
{% endblock %}

site_for_learning/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Products list' %}
{% endblock %}

{% block body %}
  <h1> {% translate 'Products' %}: </h1>
  <div>
      {% blocktranslate count product_count=products|length %}
         There is only one product
         {% plural %}
         There are {{ product_count }} products.
      {% endblocktranslate %}
  </div>

  <div>
    <ul>
        {% for product in products %}
          <li>
              <a href="{% url 'shopapp:product_details' pk=product.pk %}">
               {% translate 'Name' context 'product name' %}: {{ product.name }} </a>
               {% translate 'Price' %}: {{product.price}}
               {% translate 'no discount' as no_discount %}
               {% translate 'Discount' %}: {% firstof product.discount no_discount %}
               {% translate 'Created by' %}: {{ product.created_by }}

              {% if product.preview %}
                <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
              {% endif %}

          </li>
        {% empty %}
          {% translate 'No products' %}
        {% endfor %}
    </ul>
  </div>

  <div>
      {% url 'shopapp:product_create' as shop_product_create_url %}

      {% if "shopapp.add_product" in perms %}
        {% blocktranslate %}
              <a href="{{shop_product_create_url}}">
                  Create a new product
              </a>
        {% endblocktranslate %}
      {% endif %}

  </div>
{% endblock %}

</html>